### ISSUE TITLE
GLFW binding for LuaJIT

### ISSUE THREAD

**Issue by Playermet** [glfw/website#20]
Hello! I wrote a GLFW v3.1.0 binding for LuaJIT, and would suggest that you add a reference to it in the list on the site.

Bind uses FFI, and covers the entire API. Windows, monitors, and cursors have an alternative OOP-styled interface. Constants may used as table members (glfw.const.version_major) or strings ('version_major').

Link: https://github.com/Playermet/luajit-glfw

Sorry for bad english. :(

**Comment by elmindreda** [comment]
How would you like your name listed?

**Comment by Playermet** [comment]
Oleg Dudka.
