### ISSUE TITLE
32-bit MinGW binaries not compatible with legacy MinGW

### ISSUE THREAD

**Issue by bornskilled200** [glfw/website#24]
Windows binaries claims to have mingw/mingw-w64 libraries. However the one folder was built using mingw-w64.

This build is unusable in mingw environment. This is because vsnprintf is not defined in mingw.

I have only checked mingw 32 bit. I am not sure if there is a 64 bit build for mingw.

```
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../..\libglfw3.a(init.c.obj):init.c:(.text+0x49): undefined reference to `__ms_vsnprintf'
```

**Comment by elmindreda** [comment]
Fixed for future releases with glfw/scripts@e85b989ee7b2968319ac66e1c05d5e0caa3fdfcc.
