### ISSUE TITLE
GLFW binding for Duktape (javascript)

### ISSUE THREAD

**Issue by lzubiaur** [glfw/website#27]
Hi, I made a GLFW binding for [Duktape](http://duktape.org/) (embeddable Javascript engine) available [here](https://github.com/lzubiaur/duk-glfw).
Regards,
Laurent

**Comment by siavashserver** [comment]
Thank you, it will be accessible after next website rebuild!

**Comment by lzubiaur** [comment]
Thanks!

**Comment by elmindreda** [comment]
The site has been updated. Thanks!
