### ISSUE TITLE
http://www.glfw.org/ site down

### ISSUE THREAD

**Issue by jnareb** [glfw/website#29]
I'm not sure if it is a proper place to notify about this problem, but http://www.glfw.org/ (which I assume is generated out of those sources) is down, returning 404 Not Found for every page.

**Comment by elmindreda** [comment]
This is a great place. Thank you for reporting it! It's back up now.

**Comment by siavashserver** [comment]
@elmindreda That got me worried too, was it under maintenance?

**Comment by siavashserver** [comment]
@elmindreda Oh, and are you alright? :)

**Comment by elmindreda** [comment]
@siavashserver I missed that the new version of the Apache package changed the pattern for `sites-enabled` files just before I went offline for a full day. :+1:

Fine, thank you. You too, I hope?

**Comment by siavashserver** [comment]
@elmindreda Yup, I'm fine as well, thanks!
