### ISSUE TITLE
C++ binding

### ISSUE THREAD

**Issue by giorgiomarcias** [glfw/website#30]
Hello,
I've made a C++11 GLFW wrapper providing some extra functionality, like multi-threaded window rendering and window grouping.

Language: C++
Mantener: Giorgio Marcias
[GLFWM](https://github.com/giorgiomarcias/glfwm)

**Comment by elmindreda** [comment]
This isn't a binding, but there should be a place for wrappers like this. It looks really nice.

**Comment by siavashserver** [comment]
What about turning the *Media* page into *Insert New Name Here* and move bindings + projects making use of GLFW there?

**Comment by elmindreda** [comment]
@siavashserver That is a great idea!

**Comment by siavashserver** [comment]
Alright, I'll try to come up with a prototype in upcoming days :)

**Comment by giorgiomarcias** [comment]
@elmindreda you're right, it's not a binding, just a wrapper. But thank you very much :)
@siavashserver that sounds cool!

**Comment by realvictorprm** [comment]
Sounds interesting, would like to see this on the website too!

**Comment by elmindreda** [comment]
GLFWM has been [added](http://www.glfw.org/community.html) to a new section.

Sorry about the delay.
