### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by FlorianRhiem** [glfw/website#31]
I'm maintaining Python bindings that are quite close to the original API, but with some small changes to make better use of Pythons features and to be more "pythonic". The changes (copied from the readme) are:

 - function names use the pythonic `words_with_underscores` notation instead of `camelCase`
 - `GLFW_` and `glfw` prefixes have been removed, as their function is replaced by the module namespace
 - structs have been replaced with Python sequences
 - functions like `glfwGetMonitors` return a list instead of a pointer and an object count
 - Gamma ramps use floats between 0.0 and 1.0 instead of unsigned shorts
 - GLFW errors are reported as `glfw.GLFWError` exceptions if no error callback is set (use `glfw.ERROR_REPORTING=False` to disable this)

---

Language: Python
Maintainer: Florian Rhiem
Website: https://github.com/FlorianRhiem/pyGLFW or https://pypi.python.org/pypi/glfw

**Comment by siavashserver** [comment]
Thank you!
