### ISSUE TITLE
Progress meter shows wrong milestone

### ISSUE THREAD

**Issue by elmindreda** [glfw/website#33]
It shows 3.4 while the lexically smallest open milestone is 3.3.

**Comment by siavashserver** [comment]
This is caused by GitHub still listing *3.2.1* in open milestones, and something weird happening during version sorting.

I'm going to fix it by discarding milestones with *Major.Minor.Patch* version strings and only taking *Major.Minor* into account.

**Comment by elmindreda** [comment]
Thank you for the quick fix! Site has been updated.

> I'm going to fix it by discarding milestones with Major.Minor.Patch version strings and only taking Major.Minor into account.

Noted, and I suspect people are more interested in feature releases anyway. :smile:

**Comment by siavashserver** [comment]
No problem ^^
