### ISSUE TITLE
Possible inconsistency in the guide about when event callbacks may occur

### ISSUE THREAD

**Issue by jmegaffin** [glfw/website#34]
The API introduction says:
> Because event processing must be performed on the main thread, all callbacks except for the error callback will only be called on that thread.

The input guide says:
> Do not assume that callbacks will only be called through either of the above functions [`glfwPollEvents` & `glfwWaitEvent`]. While it is necessary to process events in the event queue, some window systems will send some events directly to the application, which in turn causes callbacks to be called outside of regular event processing.

I do not understand how both of these can be true.  If they somehow are, I think there needs to be some more explanation and clarification (for instance, "some window systems will send some events directly to the application" does not suggest the possibility that callbacks may be fired when certain GLFW functions are called).  If not, it needs to be one or the other.

**Comment by elmindreda** [comment]
This should have been filed in the glfw/glfw issue tracker because that's where the documentation sources are. Sorry, I should add a CONTRIBUTING.md to this tracker as well.

**Comment by elmindreda** [comment]
> I do not understand how both of these can be true.

Some GLFW functions call OS functions that in turn call callbacks GLFW has registered with the OS, passing to them events that GLFW then pass on to application callbacks.

application -> GLFW -> OS -> GLFW -> application

> If they somehow are, I think there needs to be some more explanation and clarification

True. Will fix.

**Comment by elmindreda** [comment]
Have a look at glfw/glfw@766a9dc9fd9c9898496b7d7b30f1d182d8fe8a6d.

**Comment by jmegaffin** [comment]
Great, thanks, that clears it up.
