### ISSUE TITLE
Newer .NET binding

### ISSUE THREAD

**Issue by realvictorprm** [glfw/website#37]
Hello developers,
I would like to see my [GLFW3.NET](https://github.com/realvictorprm/GLFW3.NET) binding referenced for .NET which is more up to date than the other bindings listed.

**Comment by elmindreda** [comment]
Thank you! Who should I list as the maintainer?

**Comment by realvictorprm** [comment]
Currently I suppose it's me 😄

**Comment by elmindreda** [comment]
I can't find your name. Should I use your username?

**Comment by realvictorprm** [comment]
You can use this one: _Victor P. R. Müller_

**Comment by elmindreda** [comment]
Thanks! Should I list it as C# or .NET?

**Comment by realvictorprm** [comment]
Actual C# bindings are .NET bindings because they're all compiled to the same intermediate language. Therefore it should be listed as .NET

**Comment by elmindreda** [comment]
The site has been updated.

**Comment by realvictorprm** [comment]
Thank you very much @elmindreda. I feel honored and try to keep it up even more!
