### ISSUE TITLE
add perl OpenGL::GLFW module to list of GLFW3 bindings

### ISSUE THREAD

**Issue by devel-chm** [glfw/website#41]
See the GLFW Forum post titled "**OpenGL::GLFW 0.03 perl bindings released to CPAN**" for details.

**Comment by elmindreda** [comment]
This has been added with eb8a2c1dcadcc92c410ea751dff89318c77cadbc. Thank you!

I can't rebuild the website from here, but will try to do so tomorrow.

**Comment by elmindreda** [comment]
The website has been [updated](http://www.glfw.org/community.html). Sorry about the delay.

**Comment by devel-chm** [comment]
Is there a GLFW announce about the addition or could you post to the
discourse topic so folks are aware it is now "official".

Thanks much,
Chris

**Comment by elmindreda** [comment]
You're right. Will do (and for any future bindings).
