### ISSUE TITLE
There is a new (more complete) binding for Red language

### ISSUE THREAD

**Issue by Oldes** [glfw/website#42]
You can find it here: https://github.com/red/code/tree/master/Library/GLFW

**Comment by elmindreda** [comment]
Thank you, will add it to the list. What is its name?

**Comment by Oldes** [comment]
It has no name.. it is just a binding for glfw lib. Which is more recent and more complete than the one which is alrady listed.

**Comment by elmindreda** [comment]
Fair enough. By what name should I credit you?

**Comment by Oldes** [comment]
If it must be, you can use [the one which is in code](https://github.com/red/code/blob/master/Library/GLFW/glfw3.reds#L3)

**Comment by Oldes** [comment]
It is your work anyway.. I just converted it into format readable from Red/System ;-)

**Comment by elmindreda** [comment]
Bindings may not be large in bytes, but they're definitely large in impact ^^

**Comment by elmindreda** [comment]
> If it must be

I can leave out the name entirely if you prefer.

**Comment by Oldes** [comment]
Oh.. common... don't  loose time on it so much.. use Oldes... it is the last thing I care about. I would rather like to know, why my Vulkan test with GLFW (just creating Vulkan instance) starts so slowly (much slowly then GL tests).. if it is some problem on my side, problem in GLFW or in something else:/

**Comment by elmindreda** [comment]
That's an odd bug. Run a profiler if you have one and see where it points. For questions I'd recommend a place like /r/vulkan or `##vulkan` on Freenode.
