### ISSUE TITLE
Apparent error in CMake 3.3.2/Unix build guide

### ISSUE THREAD

**Issue by Postski** [glfw/website#46]
From: http://www.glfw.org/docs/latest/build_guide.html

(relevant text is bold)
> If OpenGL is found, the OPENGL_FOUND variable is true and the OPENGL_INCLUDE_DIR and OPENGL_gl_LIBRARY cache variables can be used.
> 
>  **target_include_directories(myapp ${OPENGL_INCLUDE_DIR})**
>  target_link_libraries(myapp ${OPENGL_gl_LIBRARY})
> 
> The OpenGL CMake package also looks for GLU. If GLU is found, the OPENGL_GLU_FOUND variable is true and the OPENGL_INCLUDE_DIR and OPENGL_glu_LIBRARY cache variables can be used.

Fails with CMake version 3.3.2 as follows:

```
CMake Error at CMakeLists.txt:12 (target_include_directories):
  target_include_directories called with invalid arguments
```

Changing the bold line to
`target_include_directories(main PUBLIC ${OPENGL_INCLUDE_DIR})`
seems to fix the issue.

**Comment by elmindreda** [comment]
@Postski Thank you! This has been fixed with glfw/glfw@b4c99aacd46fb472b9e9c604fff245ffb21af11d by @siavashserver.
