### ISSUE TITLE
C# Wrapper for .NET Standard

### ISSUE THREAD

**Issue by ForeverZer0** [glfw/website#47]
I recently created a complete C# wrapper around the current version.

The link on website directed me here to propose it be listed on the site in the language bindings area.

[GitHub Source Code](https://github.com/ForeverZer0/glfw-net)

[Nuget Package](https://www.nuget.org/packages/glfw-net/)

**Comment by siavashserver** [comment]
Hello! Please provide your **First name** and **Last name** so we can list you there as well.

Cheers!

**Comment by ForeverZer0** [comment]
Eric Freed

Thanks so much, and thanks to the GLFW dev team for such a great API!

**Comment by siavashserver** [comment]
@ForeverZer0 It should be up and ready once reviewed by @elmindreda :)

**Comment by elmindreda** [comment]
@ForeverZer0 I'm sorry, I missed this issue. Do you still want this added and would you mind if we posted a news item about it?

**Comment by ForeverZer0** [comment]
Yes, can still list and it and post news about if desired, no problem.

Though I have not updated it to 3.3 yet, but it is on my todo list xD.

**Comment by elmindreda** [comment]
Yay! Table entry and news item are up.

**Comment by ForeverZer0** [comment]
Thank you kindly, really appreciate the fine job the GLFW team has done, and for sharing with the community.
