### ISSUE TITLE
Adding a Framework to the list

### ISSUE THREAD

**Issue by lmariscal** [glfw/website#50]
Sorry for the shameless plug, but I have been working for some months in a Nim library/framework called  [NimGL](https://github.com/lmariscal/nimgl) that is heavily inspired by LWJGL.  
The GLFW bindings are here [glfw.nim](https://github.com/lmariscal/nimgl/blob/master/src/nimgl/glfw.nim), it was implemented to be compatible with the framework and it is used as the core to make displays and the opengl context.

If you need me to modify anything please let me know 👍

**Comment by elmindreda** [comment]
Shameless plugs are most welcome! Adding it to the framework list.

Note that the nimgl.org website seems to be down.
