### ISSUE TITLE
OCaml binding.

### ISSUE THREAD

**Issue by SylvainBoilard** [glfw/website#51]
Hi,

I made an OCaml binding for GLFW and was wondering if you would add a word about it on the website.

Here is the [GitHub repository](https://github.com/SylvainBoilard/GLFW-OCaml). It is also available on [opam](https://opam.ocaml.org/packages/glfw-ocaml/glfw-ocaml.3.2.1~rc1).

This is a release-candidate version which I believe has no outstanding bugs left but hasn’t had much real testing yet.

Cheers.

**Comment by elmindreda** [comment]
Thank you!

**Comment by SylvainBoilard** [comment]
Glad to help!
