### ISSUE TITLE
Language bindings for Harbour 

### ISSUE THREAD

**Issue by rjopek** [glfw/website#53]
Hi, 

I have the honor to present binding language Harbour.
[HarbourGL](https://github.com/rjopek/harbour-gl)

[Harbour Wikipedia]( https://en.wikipedia.org/wiki/Harbour_(software) )

Best regards
-- Rafał Jopek

**Comment by elmindreda** [comment]
Was this closed by accident?

**Comment by rjopek** [comment]
This is not a problem, only informed about the existence of such bindings.  ;)

-- Rafał

**Comment by elmindreda** [comment]
I'll add it to the list then. Thanks!

**Comment by rjopek** [comment]
Thank you.

**Comment by rjopek** [comment]
I changed the name of the repository, this is the correct name for this project, 
https://github.com/rjopek/hb-glfw

whether these are active dependency?
glfw-devel{rpm}
glfw{homebrew|pkgng}
glfw{pacman}
mingw-w64-i686-glfw{msys2&x86}
mingw-w64-x86_64-glfw{msys2&x86_64}

PS.
it's a great project GLFW. 
-- Rafał

**Comment by elmindreda** [comment]
Thanks! The bindings have been added to the list under the new name.

Are these bindings feature complete? I don't know Harbour but it looks like some functions are still not fully implemented.

**Comment by rjopek** [comment]
Hi,

Harbor is a great programming language. His story is as old as coal
This is why I am here, I would like to say more...

I'm sorry to say, binding they are not finished yet, hmm,  did some tests, the windows work very well, you can draw all objects OpenGL (almost) ; 
The project will go toward "nuklear"

**Comment by rjopek** [comment]
Thanks!
