### ISSUE TITLE
Replace D Bindings

### ISSUE THREAD

**Issue by mdparker** [glfw/website#54]
I maintained the DerelictGLFW3 D bindings for years. Recently, I've moved the project to bug-fix-only mode and have been working on a new set of bindings that take advantage of newer D features. bindbc-glfw is available at:

https://github.com/BindBC/bindbc-glfw

and should replace the DerelictGLFW3 bindings listed on the GLFW website.

Thanks!

**Comment by siavashserver** [comment]
Done, thanks for the update! :)

**Comment by elmindreda** [comment]
@siavashserver Thanks!

@mdparker Are the new bindings feature-complete, or in other words, should we make a post about them on glfw.org?

**Comment by mdparker** [comment]
@elmindreda The package is feature complete, though not fully tested (consider it a beta release). I wouldn't complain about a post :-)

**Comment by elmindreda** [comment]
Done.
