### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by elmindreda** [glfw/website#55]
GitHub pages allows us to have [our own 404 page](https://help.github.com/en/articles/creating-a-custom-404-page-for-your-github-pages-site), which could be nicer than their default one.

**Comment by siavashserver** [comment]
Hi there!

Yup, it's a good idea. Jekyll also allows us to generate a site map
automatically and make the website more search engine friendly. I wish we
could do something about pages generated by doxygen as well.

We can also set a fav-icon and custom tab color for chrome like browsers.

**Comment by elmindreda** [comment]
Yeah, Doxygen is annoying to the point where I'm almost considering replacing it with our Jekyll setup and slightly more typing.

**Comment by elmindreda** [comment]
Having even a partial site map still seems useful, I think. Would it be?

**Comment by siavashserver** [comment]
> Yeah, Doxygen is annoying to the point where I'm almost considering replacing it with our Jekyll setup and slightly more typing.

Back then Doxygen was the only viable solution, there should be much better options now. Most of the custom CSS file is just resetting the unnecessarily hard coded Doxygen style sheets.


> Having even a partial site map still seems useful, I think. Would it be?

Yes; I'll come up with a pull request in upcoming days :)

**Comment by elmindreda** [comment]
Fixed by @siavashserver with #57.
