### ISSUE TITLE
Delphi language binding

### ISSUE THREAD

**Issue by jersonSeling** [glfw/website#60]
https://github.com/neslib/DelphiGlfw

**Comment by elmindreda** [comment]
@jersonSeling Thank you!

@erikvanbilsen Would you like to have your bindings added to the list and/or announced in a glfw.org news update?

**Comment by neslib** [comment]
@elmindreda Sure you can add it to the list of bindings. I'm fine with a news update as well, even though the bindings are 3 years old...
