### ISSUE TITLE
main website page has claims without proof that should be possible to be easily added - "just two function calls"

### ISSUE THREAD

**Issue by matkoniecz** [glfw/website#67]
> Gives you a window and OpenGL context with just two function calls

is a bare claim without a link. It would be much more useful for newbies and much more convincing with "two function calls" linking to a tutorial page/gist with code presenting how this can be done.

Continuation of #64 (done because currently I am not using/contributing but based on my own experience I know that such feedback may be useful - please let me know if I am wrong)

**Comment by elmindreda** [comment]
It could be usefully linked to the [documentation page example](https://www.glfw.org/documentation.html#example-code).
