### ISSUE TITLE
I would like to introduce a new C# binding

### ISSUE THREAD

**Issue by TheBoneJarmer** [glfw/website#69]
Hi guys

A couple of years ago I started with a C# library that binds both OpenGL methods, enums and constants along with GLFW methods, constants and enums. Back than it was still a raw version, generated from the Kronos Group XML file, where not all the pInvoked signatures from the C library were correct. But over time I polished the library and I feel safe enough to say now it is quite stable. It is still in beta as not every methods have been tested. But heck, there are over 40000 in total so I did not bother to be honest. But if this works fine for others I am most definitely going to publish version 1.0.0.

My library is called _Arqan_ and can be located at https://github.com/TheBoneJarmer/Arqan.git. I already have NuGet packages in place too. Those are called Arqan.Windows and Arqan.Linux. I do not own a MacBook, nor do I plan to buy one, so I have no version for that. I actually hope the community will jump in for that matter. Anyways, let me know what you think. It would be a honor if you add my project to the bindings list. :)

Speaking of which, if anyone would wonder why to use my library over the others. Well, it all depends on your expectations. To begin with, Arqan does offer **bindings for OpenGL on top of GLFW bindings**, that is a major difference. Also, Arqan is literally nothing more and nothing less than **pInvoked methods**. Therefore the c++ examples could be easily translated to C# with an exception to the callbacks, which are delegate voids. So unlike with for example ForeverZer0's library, **you do need to write your own window and input classes**. But I included examples so you don't have to figure that one out yourself.

With kind regards,
TheBoneJarmer

**Comment by siavashserver** [comment]
Done, thanks for sharing! :)

**Comment by TheBoneJarmer** [comment]
Hi @siavashserver 

Thanks a lot for adding Arqan to the list! I really appreciate it. I do have a question though, how long will it take for the website to update? You pushed your commit over a week ago but glfw.org has not changed since.

With kind regards,
TheBoneJarmer

**Comment by siavashserver** [comment]
Hello dear Ruben, sorry about inconvenience, all changes will go online
once reviewed by @elmindreda . She's probably busy with more important
matters.

Best regards,
Siavash Eliasi.

**Comment by TheBoneJarmer** [comment]
Hello @siavashserver 

Aaah ok! No problem at all, thanks for the fast reply!

With kind regards,
TheBoneJarmer
