### ISSUE TITLE
Yet another Node.js NAPI binding

### ISSUE THREAD

**Issue by raub** [glfw/website#75]
https://github.com/node-3d/glfw-raub

This one has actually been around for quite a while. It started as a fork of an old addon, but was then rewritten to NAPI.

The binding also has some optional higher-level API's and is somewhat documented. It's now a part of Node3D project, and is used as such by this Steam-distributed game: https://store.steampowered.com/app/1196080/Space_Simulation_Toolkit/

**Comment by siavashserver** [comment]
Thank you!
