### ISSUE TITLE
New C++17 header-only wrapper

### ISSUE THREAD

**Issue by janekb04** [glfw/website#76]
Hi, I have created a header-only C++17 wrapper for GLFW 3.3. It is quite thin because I like thin wrappers and is as such different from the already linked GLFWM library. I am planning to add more examples to it and update to cover future versions of GLFW. Currently it is only missing functionality from `glfw3native.h`, which I plan to add soon.
The library should be fairly stable, but I can't guarantee that there are no issues whatsoever.
Language: C++ (17)
Author: Jan Bielak
[GLFWPP](https://github.com/janekb04/glfwpp)

**Comment by janekb04** [comment]
I think that adding this wrapper to the website would be useful as, at least I, always look for a C++ wrapper for a C library that I plan to include in my C++ projects. I usually prefer thin wrappers, such as this one, as it makes it easy to adopt them and switch from a C implementation.

**Comment by siavashserver** [comment]
Thank you very much!

**Comment by janekb04** [comment]
Thanks
